USE [master]
GO
/****** Object:  Database [MailGenieDb]    Script Date: 9/23/2025 3:17:37 PM ******/
CREATE DATABASE [MailGenieDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MailGenieDb', FILENAME = N'C:\Users\jadha\MailGenieDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MailGenieDb_log', FILENAME = N'C:\Users\jadha\MailGenieDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MailGenieDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MailGenieDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MailGenieDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MailGenieDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MailGenieDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MailGenieDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MailGenieDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [MailGenieDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MailGenieDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MailGenieDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MailGenieDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MailGenieDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MailGenieDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MailGenieDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MailGenieDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MailGenieDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MailGenieDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MailGenieDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MailGenieDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MailGenieDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MailGenieDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MailGenieDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MailGenieDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MailGenieDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MailGenieDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MailGenieDb] SET  MULTI_USER 
GO
ALTER DATABASE [MailGenieDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MailGenieDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MailGenieDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MailGenieDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MailGenieDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MailGenieDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MailGenieDb] SET QUERY_STORE = OFF
GO
USE [MailGenieDb]
GO
/****** Object:  Table [dbo].[EmailTemplate]    Script Date: 9/23/2025 3:17:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmailTemplate](
	[TemplateId] [int] IDENTITY(1,1) NOT NULL,
	[SubjectContent] [varchar](1000) NULL,
	[TemplateContent] [varchar](max) NULL,
	[TemplateType] [varchar](500) NULL,
	[Position] [varchar](200) NULL,
	[CreateDate] [datetime] NULL,
	[IsActive] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[TemplateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[EmailTemplate] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO
USE [master]
GO
ALTER DATABASE [MailGenieDb] SET  READ_WRITE 
GO
